- name: Add service configuration
  template:
    src: consul-web-demo.service.j2
    dest: /etc/systemd/system/consul-web-demo.service
    owner: root
    group: root
    mode: 0644
  become: yes
  vars:
    datacenter_name: skyhigh
  notify:
    - reload_app_service
    - restart_app_service

# `go get` is not idempotent, so we grab the checksum before and after running it
- name: Get old application checksum
  stat:
    path: /home/ubuntu/go/bin/consul-web-demo
  register: before_stat

# we force this task to never trigger "changed", we handle that ourselves
- name: Install from source
  command: /snap/bin/go get -u github.com/adrialu/consul-web-demo
  changed_when: false

- name: Get new application checksum
  stat:
    path: /home/ubuntu/go/bin/consul-web-demo
  register: after_stat

# finally compare checksums, completing the idempotency issues with `go get`
- name: Compare checksums
  when: '"checksum" not in before_stat.stat or before_stat.stat.checksum != after_stat.stat.checksum'
  changed_when: '"checksum" not in before_stat.stat or before_stat.stat.checksum != after_stat.stat.checksum'
  debug:
    msg: "Detected application change"
  notify:
    - restart_app_service

- name: Start application service
  service:
    name: consul-web-demo
    enabled: yes
    state: started
  become: yes

# we register the application as a service with Consul, so Fabio knows what service to proxy for
- name: Register service with Consul
  template:
    src: web.json.j2
    dest: /etc/consul.d/web.json
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart_consul
