- name: Add server configuration
  template:
    src: consul_server.json.j2
    dest: /etc/consul.d/config.json
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart_consul_service

# the resolved service has bound port 53, preventing Consul from acting as a DNS
- name: Disable resolved service
  service:
    name: systemd-resolved
    enabled: no
    state: stopped
  become: yes

- name: Start service
  service:
    name: consul
    enabled: yes
    state: started
  become: yes
