---
- name: create folders
  file:
    path: /etc/consul.d
    state: directory
    mode: 0755
  become: yes

- name: Setup consul config
  template:
    src: consul_cluster.json.j2
    dest: /etc/consul.d/config.json
    owner: root
    group: root
    mode: 0644
    validate: 'consul validate /etc/consul.d'
  become: yes
  notify: restart_consul_service

- name: Disable resolved
  service:
    name: systemd-resolved
    enabled: no
    state: stopped
  become: yes

- name: Start consul service
  service:
    name: consul
    enabled: yes
    state: started
  become: yes
