- name: Install from archive
  unarchive:
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  vars:
    consul_version: 1.3.0
  become: yes

- name: Add service configuration
  template:
    src: consul.service.tpl
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: reload_consul_service

- name: Create configuration directories
  file:
    path: /etc/consul.d
    state: directory
    mode: 0755
  become: yes

