---
# Handles base package setup:
- name: Installing base packages
  apt:
    # Install a set of packages with latest version, update cache at the same time
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    # Add vim,tmux,htop just to demonstrate
    packages:
      - vim
      - tmux
      - htop
  become: yes

# Handles timezone setup (NTP package might be overkill?)
- name: Set timezone to Europe/Oslo
  timezone:
    name: Europe/Oslo
  become: yes

# Copy custom .vimrc
- name: Add vimrc
  copy:
    src: ../templates/vimrc.tpl
    dest: /home/ubuntu/.vimrc
    owner: ubuntu
    group: ubuntu
    mode: 0664

# Copy custom .bashrc
- name: Add bashrc
  copy:
    src: ../templates/bashrc.tpl
    dest: /home/ubuntu/.bashrc
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Get and unzip consul
  unarchive:
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/local/bin
    mode: 755
    owner: root
    group: root
    remote_src: yes
  become: yes
