---
# Add Haproxy repo
- name: install | add repository from PPA and install its signing key
  apt_repository:
    repo: "{{ haproxy_ppa }}"
    update_cache: true
  become: yes

# Install the package
- name: install haproxy
  apt:
    name: haproxy
    state: latest
  become: yes

# add haproxy config
- name: add haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
    validate: 'haproxy -f %s -c'
  become: yes
  notify:
    - restart-haproxy

# enable and start haproxy service
- name: enable and start haproxy service
  service:
    name: haproxy
    state: started
    enabled: yes
  become: yes
