- name: Add service configuration
  template:
    src: fabio.service.j2
    dest: /etc/systemd/system/fabio.service
    owner: root
    group: root
    mode: 0644
  become: yes
  vars:
    datacenter_name: skyhigh
  notify:
    - reload_fabio_service
    - restart_fabio_service

# `go get` is not idempotent, so we grab the checksum before and after running it
- name: Get old application checksum
  stat:
    path: /home/ubuntu/go/bin/fabio
  register: before_stat

# we force this task to never trigger "changed", we handle that ourselves
- name: Install from source
  command: /snap/bin/go get -u github.com/fabiolb/fabio
  changed_when: false

- name: Get new application checksum
  stat:
    path: /home/ubuntu/go/bin/fabio
  register: after_stat

# finally compare checksums, completing the idempotency issues with `go get`
- name: Compare checksums
  when: '"checksum" not in before_stat.stat or before_stat.stat.checksum != after_stat.stat.checksum'
  changed_when: '"checksum" not in before_stat.stat or before_stat.stat.checksum != after_stat.stat.checksum'
  debug:
    msg: "Detected application change"
  notify:
    - restart_fabio_service

- name: Start application service
  service:
    name: fabio
    enabled: yes
    state: started
  become: yes
