# snap packages are not supported in Ansible until 2.8,
# so we've imported it from devel into /library
# https://docs.ansible.com/ansible/devel/modules/snap_module.html
- name: Install Go
  snap:
    name: go
    classic: yes
  become: yes
