- name: Add VIM configuration
  template:
    src: vimrc.tpl
    dest: /home/ubuntu/.vimrc
    owner: ubuntu
    group: ubuntu
    mode: 0664

- name: Add Bash configuration
  template:
    src: bashrc.tpl
    dest: /home/ubuntu/.bashrc
    owner: ubuntu
    group: ubuntu
    mode: 0644
