- name: Install from archive
  unarchive:
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  vars:
    consul_version: 1.3.0
  become: yes