- name: reload_app_service
  systemd:
    daemon_reload: yes
  become: yes

- name: restart_app_service
  service:
    name: consul-web-demo
    state: restarted
  become: yes

- name: restart_consul
  service:
    name: consul
    state: restarted
  become: yes
