- name: reload-app-service
  systemd:
    daemon_reload: yes
  become: yes

- name: restart-app-service
  service:
    name: consul-web-demo
    state: restarted
  become: yes

- name: restart-consul
  service:
    name: consul
    state: restarted
  become: yes
