# All hosts
- hosts: all
  roles:
    - common
    - dotfiles
    - netplan
    - consul

# All consul servers
- hosts: consul
  roles:
    - consul-server

# Set up consul agents on all hosts except for the consul servers
- hosts: all:!consul
  roles:
    - consul-client

# install go on proxy and web servers
- hosts: proxy:web
  roles:
    - go

# install the web app on the web servers
- hosts: web
  roles:
    - webapp

# install fabio on the proxy servers
- hosts: proxy
  roles:
    - fabio
