# install applications and configure them for all hosts
- hosts: all
  roles:
    - common
    - dotfiles
    - netplan
    - consul

# separate the consul servers from the rest with separate roles
- hosts: consul
  roles:
    - consul-server

- hosts: all:!consul
  roles:
    - consul-client


- hosts: proxy:web
  roles:
    - go

- hosts: web
  roles:
    - webapp

- hosts: proxy
  roles:
    - fabio
