# All hosts
- hosts: all
  roles:
    - common
    - dotfiles
    - netplan
    - consul

# All haproxy servers
- hosts: haproxy
  roles:
    - haproxy

# All consul servers
- hosts: consul
  roles:
    - consul-server

# Set up consul agents on all hosts except for the consul servers
- hosts: all:!consul
  roles:
    - consul-client
