# All hosts
- hosts: all
  roles:
    - common
    - netplan
    - consul

# All haproxy servers
- hosts: haproxy
  roles:
    - haproxy

# All consul servers
- hosts: consul
  roles:
    - consul-server
